/*
An Open route generated by express, simply prints a hello world type greeting, can be used to test if the backend is live
*/
var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function (req, res, next) {
  res.render('index', { title: 'Express' });
});

module.exports = router;
