environment: {}
parameters: {}
packages:
  - name: Admin
    functions:
      - name: hello
        runtime: 'nodejs:default'
        web: false
  - name: Auditor
    functions:
      - name: hello
        runtime: 'nodejs:default'
        web: false
  - name: ComplianceManager
    functions:
      - name: hello
        runtime: 'nodejs:default'
        web: false
  - name: Shared
    functions:
      - name: hello
        runtime: 'nodejs:default'
        web: false